name: Build and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SKL:

    runs-on: intel-ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install g++-13 libgtest-dev meson curl git cmake

    - name: Install google benchmarks
      run: |
        git clone https://github.com/google/benchmark.git
        cd benchmark
        cmake -E make_directory "build"
        cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release ../
        sudo cmake --build "build" --config Release --target install

    - name: Install Intel SDE
      run: |
        curl -o /tmp/sde.tar.xz https://downloadmirror.intel.com/784319/sde-external-9.24.0-2023-07-13-lin.tar.xz
        mkdir /tmp/sde && tar -xvf /tmp/sde.tar.xz -C /tmp/sde/
        sudo mv /tmp/sde/* /opt/sde && sudo ln -s /opt/sde/sde64 /usr/bin/sde

    - name: Build
      env:
        CXX: g++-13
      run: |
        make clean
        meson setup --warnlevel 2 --werror --buildtype release builddir
        cd builddir
        ninja

    - name: Run test suite on SKL
      run: sde -skl -- ./builddir/testexe

  SKX:

    runs-on: intel-ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install g++-13 libgtest-dev meson curl git cmake

    - name: Install google benchmarks
      run: |
        git clone https://github.com/google/benchmark.git
        cd benchmark
        cmake -E make_directory "build"
        cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release ../
        sudo cmake --build "build" --config Release --target install

    - name: Install Intel SDE
      run: |
        curl -o /tmp/sde.tar.xz https://downloadmirror.intel.com/784319/sde-external-9.24.0-2023-07-13-lin.tar.xz
        mkdir /tmp/sde && tar -xvf /tmp/sde.tar.xz -C /tmp/sde/
        sudo mv /tmp/sde/* /opt/sde && sudo ln -s /opt/sde/sde64 /usr/bin/sde

    - name: Build
      env:
        CXX: g++-13
      run: |
        make clean
        meson setup --warnlevel 2 --werror --buildtype release builddir
        cd builddir
        ninja

    - name: Run test suite on SKX
      run: sde -skx -- ./builddir/testexe

  TGL:

    runs-on: intel-ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install g++-13 libgtest-dev meson curl git cmake

    - name: Install google benchmarks
      run: |
        git clone https://github.com/google/benchmark.git
        cd benchmark
        cmake -E make_directory "build"
        cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release ../
        sudo cmake --build "build" --config Release --target install

    - name: Install Intel SDE
      run: |
        curl -o /tmp/sde.tar.xz https://downloadmirror.intel.com/784319/sde-external-9.24.0-2023-07-13-lin.tar.xz
        mkdir /tmp/sde && tar -xvf /tmp/sde.tar.xz -C /tmp/sde/
        sudo mv /tmp/sde/* /opt/sde && sudo ln -s /opt/sde/sde64 /usr/bin/sde

    - name: Build
      env:
        CXX: g++-13
      run: |
        make clean
        meson setup --warnlevel 2 --werror --buildtype release builddir
        cd builddir
        ninja
    - name: Run test suite on TGL
      run: sde -tgl -- ./builddir/testexe

  SPR:

    runs-on: intel-ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install g++-13 libgtest-dev meson curl git cmake

    - name: Install google benchmarks
      run: |
        git clone https://github.com/google/benchmark.git
        cd benchmark
        cmake -E make_directory "build"
        cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release ../
        sudo cmake --build "build" --config Release --target install

    - name: Install Intel SDE
      run: |
        curl -o /tmp/sde.tar.xz https://downloadmirror.intel.com/784319/sde-external-9.24.0-2023-07-13-lin.tar.xz
        mkdir /tmp/sde && tar -xvf /tmp/sde.tar.xz -C /tmp/sde/
        sudo mv /tmp/sde/* /opt/sde && sudo ln -s /opt/sde/sde64 /usr/bin/sde

    - name: Build
      env:
        CXX: g++-13
      run: |
        make clean
        meson setup --warnlevel 2 --werror --buildtype release builddir
        cd builddir
        ninja

    - name: Run test suite on SPR
      run: sde -spr -- ./builddir/testexe
